version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"                  # Enable Traefik for this service
      - "traefik.http.routers.nextjs.rule=Host(`learn.54krd.ru`)" # Route by domain name
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000" # Target app's internal port
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextjs.middlewares=redirect-to-https"
      - "traefik.docker.network=bitrix-common_bitrix"
    volumes:
      - "./../:/"
    environment:
      - NODE_ENV=production
    depends_on:
      - bitrix-common-traefik