# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy only the package.json and package-lock.json to install dependencies

# Build the Next.js application


# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start"]
